package generator

import (
	"strings"
	"text/template"
)

const (
	entityContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/lite-lake/litecore-go/container"
	{{- if .Components}}
	"github.com/lite-lake/litecore-go/common"
	{{- end}}
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitEntityContainer Initialize entity container
func InitEntityContainer() *container.EntityContainer {
	entityContainer := container.NewEntityContainer()

	{{- range .Components}}
	container.RegisterEntity[common.IBaseEntity](entityContainer, &{{.PackageAlias}}.{{.TypeName}}{})
	{{- end}}

	return entityContainer
}
`

	repositoryContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/lite-lake/litecore-go/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitRepositoryContainer Initialize repository container
func InitRepositoryContainer(entityContainer *container.EntityContainer) *container.RepositoryContainer {
	repositoryContainer := container.NewRepositoryContainer(entityContainer)

	{{- range .Components}}
	container.RegisterRepository[{{.InterfaceType}}](repositoryContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return repositoryContainer
}
`

	serviceContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/lite-lake/litecore-go/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitServiceContainer Initialize service container
func InitServiceContainer(repositoryContainer *container.RepositoryContainer) *container.ServiceContainer {
	serviceContainer := container.NewServiceContainer(repositoryContainer)

	{{- range .Components}}
	container.RegisterService[{{.InterfaceType}}](serviceContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return serviceContainer
}
`

	controllerContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/lite-lake/litecore-go/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitControllerContainer Initialize controller container
func InitControllerContainer(serviceContainer *container.ServiceContainer) *container.ControllerContainer {
	controllerContainer := container.NewControllerContainer(serviceContainer)

	{{- range .Components}}
	container.RegisterController[{{.InterfaceType}}](controllerContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return controllerContainer
}
`

	middlewareContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/lite-lake/litecore-go/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitMiddlewareContainer Initialize middleware container
func InitMiddlewareContainer(serviceContainer *container.ServiceContainer) *container.MiddlewareContainer {
	middlewareContainer := container.NewMiddlewareContainer(serviceContainer)

	{{- range .Components}}
	container.RegisterMiddleware[{{.InterfaceType}}](middlewareContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return middlewareContainer
}
`

	listenerContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/lite-lake/litecore-go/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitListenerContainer Initialize listener container
func InitListenerContainer(serviceContainer *container.ServiceContainer) *container.ListenerContainer {
	listenerContainer := container.NewListenerContainer(serviceContainer)

	{{- range .Components}}
	container.RegisterListener[{{.InterfaceType}}](listenerContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return listenerContainer
}
`

	schedulerContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/lite-lake/litecore-go/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitSchedulerContainer Initialize scheduler container
func InitSchedulerContainer(serviceContainer *container.ServiceContainer) *container.SchedulerContainer {
	schedulerContainer := container.NewSchedulerContainer(serviceContainer)

	{{- range .Components}}
	container.RegisterScheduler[{{.InterfaceType}}](schedulerContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return schedulerContainer
}
`

	engineTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/lite-lake/litecore-go/server"
)

// NewEngine Create application engine
func NewEngine() (*server.Engine, error) {
	entityContainer := InitEntityContainer()
	repositoryContainer := InitRepositoryContainer(entityContainer)
	serviceContainer := InitServiceContainer(repositoryContainer)
	controllerContainer := InitControllerContainer(serviceContainer)
	middlewareContainer := InitMiddlewareContainer(serviceContainer)
	listenerContainer := InitListenerContainer(serviceContainer)
	schedulerContainer := InitSchedulerContainer(serviceContainer)

	return server.NewEngine(
		&server.BuiltinConfig{
			Driver:   "yaml",
			FilePath: "{{.ConfigPath}}",
		},
		entityContainer,
		repositoryContainer,
		serviceContainer,
		controllerContainer,
		middlewareContainer,
		listenerContainer,
		schedulerContainer,
	), nil
}
`
)

var (
	entityContainerTmpl     *template.Template
	repositoryContainerTmpl *template.Template
	serviceContainerTmpl    *template.Template
	controllerContainerTmpl *template.Template
	middlewareContainerTmpl *template.Template
	listenerContainerTmpl   *template.Template
	schedulerContainerTmpl  *template.Template
	engineTmpl              *template.Template
)

func init() {
	entityContainerTmpl = template.Must(template.New("entity_container").Parse(entityContainerTemplate))
	repositoryContainerTmpl = template.Must(template.New("repository_container").Parse(repositoryContainerTemplate))
	serviceContainerTmpl = template.Must(template.New("service_container").Parse(serviceContainerTemplate))
	controllerContainerTmpl = template.Must(template.New("controller_container").Parse(controllerContainerTemplate))
	middlewareContainerTmpl = template.Must(template.New("middleware_container").Parse(middlewareContainerTemplate))
	listenerContainerTmpl = template.Must(template.New("listener_container").Parse(listenerContainerTemplate))
	schedulerContainerTmpl = template.Must(template.New("scheduler_container").Parse(schedulerContainerTemplate))
	engineTmpl = template.Must(template.New("engine").Parse(engineTemplate))
}

// TemplateData 模板数据
type TemplateData struct {
	PackageName string
	ConfigPath  string
	Imports     map[string]string
	Components  []ComponentTemplateData
}

// ComponentTemplateData 组件模板数据
type ComponentTemplateData struct {
	TypeName      string
	InterfaceName string
	InterfaceType string
	PackagePath   string
	PackageAlias  string
	FactoryFunc   string
	Layer         string
}

// GenerateEntityContainer 生成实体容器代码
func GenerateEntityContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := entityContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateRepositoryContainer 生成仓储容器代码
func GenerateRepositoryContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := repositoryContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateServiceContainer 生成服务容器代码
func GenerateServiceContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := serviceContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateControllerContainer 生成控制器容器代码
func GenerateControllerContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := controllerContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateMiddlewareContainer 生成中间件容器代码
func GenerateMiddlewareContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := middlewareContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateListenerContainer 生成监听器容器代码
func GenerateListenerContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := listenerContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateSchedulerContainer 生成定时器容器代码
func GenerateSchedulerContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := schedulerContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateEngine 生成引擎代码
func GenerateEngine(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := engineTmpl.Execute(&sb, data)
	return sb.String(), err
}
