package generator

import (
	"strings"
	"text/template"
)

const (
	configContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"com.litelake.litecore/common"
	"com.litelake.litecore/container"
	{{- if .Components}}
	{{- else}}
	"com.litelake.litecore/config"
	{{- end}}
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitConfigContainer 初始化配置容器
func InitConfigContainer() (*container.ConfigContainer, error) {
	configContainer := container.NewConfigContainer()

	{{- if .Components}}
	configProvider, err := {{(index .Components 0).PackageAlias}}.{{(index .Components 0).FactoryFunc}}()
	{{- else}}
	configProvider, err := config.NewConfigProvider("yaml", "{{.ConfigPath}}")
	{{- end}}
	if err != nil {
		return nil, err
	}

	container.RegisterConfig[common.IBaseConfigProvider](configContainer, configProvider)

	return configContainer, nil
}
`

	entityContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"com.litelake.litecore/common"
	"com.litelake.litecore/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitEntityContainer 初始化实体容器
func InitEntityContainer() *container.EntityContainer {
	entityContainer := container.NewEntityContainer()

	{{- range .Components}}
	container.RegisterEntity[common.IBaseEntity](entityContainer, &{{.PackageAlias}}.{{.TypeName}}{})
	{{- end}}

	return entityContainer
}
`

	managerContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"reflect"

	"com.litelake.litecore/common"
	"com.litelake.litecore/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitManagerContainer 初始化管理器容器
func InitManagerContainer(configContainer *container.ConfigContainer) (*container.ManagerContainer, error) {
	managerContainer := container.NewManagerContainer(configContainer)

	configProvider := configContainer.GetByType(reflect.TypeOf((*common.IBaseConfigProvider)(nil)).Elem())
	_ = configProvider

	{{- range .Components}}
	manager{{.TypeName}}, err := {{.PackageAlias}}.{{.FactoryFunc}}(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[{{.InterfaceType}}](managerContainer, manager{{.TypeName}})
	{{- end}}

	return managerContainer, nil
}
`

	repositoryContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"com.litelake.litecore/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitRepositoryContainer 初始化仓储容器
func InitRepositoryContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	entityContainer *container.EntityContainer,
) *container.RepositoryContainer {
	repositoryContainer := container.NewRepositoryContainer(configContainer, managerContainer, entityContainer)

	{{- range .Components}}
	container.RegisterRepository[{{.InterfaceType}}](repositoryContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return repositoryContainer
}
`

	serviceContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"com.litelake.litecore/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitServiceContainer 初始化服务容器
func InitServiceContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	repositoryContainer *container.RepositoryContainer,
) *container.ServiceContainer {
	serviceContainer := container.NewServiceContainer(configContainer, managerContainer, repositoryContainer)

	{{- range .Components}}
	container.RegisterService[{{.InterfaceType}}](serviceContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return serviceContainer
}
`

	controllerContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"com.litelake.litecore/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitControllerContainer 初始化控制器容器
func InitControllerContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	serviceContainer *container.ServiceContainer,
) *container.ControllerContainer {
	controllerContainer := container.NewControllerContainer(configContainer, managerContainer, serviceContainer)

	{{- range .Components}}
	container.RegisterController[{{.InterfaceType}}](controllerContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return controllerContainer
}
`

	middlewareContainerTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"com.litelake.litecore/container"
	{{- range $alias, $path := .Imports}}
	{{- if $alias}}
	{{ $alias }} "{{$path}}"
	{{- else}}
	"{{$path}}"
	{{- end}}
	{{- end}}
)

// InitMiddlewareContainer 初始化中间件容器
func InitMiddlewareContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	serviceContainer *container.ServiceContainer,
) *container.MiddlewareContainer {
	middlewareContainer := container.NewMiddlewareContainer(configContainer, managerContainer, serviceContainer)

	{{- range .Components}}
	container.RegisterMiddleware[{{.InterfaceType}}](middlewareContainer, {{.PackageAlias}}.{{.FactoryFunc}}())
	{{- end}}

	return middlewareContainer
}
`

	engineTemplate = `// Code generated by litecore/cli. DO NOT EDIT.
package {{.PackageName}}

import (
	"com.litelake.litecore/server"
)

// NewEngine 创建应用引擎
func NewEngine() (*server.Engine, error) {
	configContainer, err := InitConfigContainer()
	if err != nil {
		return nil, err
	}

	entityContainer := InitEntityContainer()

	managerContainer, err := InitManagerContainer(configContainer)
	if err != nil {
		return nil, err
	}

	repositoryContainer := InitRepositoryContainer(configContainer, managerContainer, entityContainer)

	serviceContainer := InitServiceContainer(configContainer, managerContainer, repositoryContainer)

	controllerContainer := InitControllerContainer(configContainer, managerContainer, serviceContainer)

	middlewareContainer := InitMiddlewareContainer(configContainer, managerContainer, serviceContainer)

	if err := managerContainer.InjectAll(); err != nil {
		return nil, err
	}
	if err := repositoryContainer.InjectAll(); err != nil {
		return nil, err
	}
	if err := serviceContainer.InjectAll(); err != nil {
		return nil, err
	}
	if err := controllerContainer.InjectAll(); err != nil {
		return nil, err
	}
	if err := middlewareContainer.InjectAll(); err != nil {
		return nil, err
	}

	return server.NewEngine(
		configContainer,
		entityContainer,
		managerContainer,
		repositoryContainer,
		serviceContainer,
		controllerContainer,
		middlewareContainer,
	), nil
}
`
)

var (
	configContainerTmpl     *template.Template
	entityContainerTmpl     *template.Template
	managerContainerTmpl    *template.Template
	repositoryContainerTmpl *template.Template
	serviceContainerTmpl    *template.Template
	controllerContainerTmpl *template.Template
	middlewareContainerTmpl *template.Template
	engineTmpl              *template.Template
)

func init() {
	configContainerTmpl = template.Must(template.New("config_container").Parse(configContainerTemplate))
	entityContainerTmpl = template.Must(template.New("entity_container").Parse(entityContainerTemplate))
	managerContainerTmpl = template.Must(template.New("manager_container").Parse(managerContainerTemplate))
	repositoryContainerTmpl = template.Must(template.New("repository_container").Parse(repositoryContainerTemplate))
	serviceContainerTmpl = template.Must(template.New("service_container").Parse(serviceContainerTemplate))
	controllerContainerTmpl = template.Must(template.New("controller_container").Parse(controllerContainerTemplate))
	middlewareContainerTmpl = template.Must(template.New("middleware_container").Parse(middlewareContainerTemplate))
	engineTmpl = template.Must(template.New("engine").Parse(engineTemplate))
}

// TemplateData 模板数据
type TemplateData struct {
	PackageName string
	ConfigPath  string
	Imports     map[string]string
	Components  []ComponentTemplateData
}

// ComponentTemplateData 组件模板数据
type ComponentTemplateData struct {
	TypeName      string
	InterfaceName string
	InterfaceType string
	PackagePath   string
	PackageAlias  string
	FactoryFunc   string
}

// GenerateConfigContainer 生成配置容器代码
func GenerateConfigContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := configContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateEntityContainer 生成实体容器代码
func GenerateEntityContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := entityContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateManagerContainer 生成管理器容器代码
func GenerateManagerContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := managerContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateRepositoryContainer 生成仓储容器代码
func GenerateRepositoryContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := repositoryContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateServiceContainer 生成服务容器代码
func GenerateServiceContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := serviceContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateControllerContainer 生成控制器容器代码
func GenerateControllerContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := controllerContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateMiddlewareContainer 生成中间件容器代码
func GenerateMiddlewareContainer(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := middlewareContainerTmpl.Execute(&sb, data)
	return sb.String(), err
}

// GenerateEngine 生成引擎代码
func GenerateEngine(data *TemplateData) (string, error) {
	var sb strings.Builder
	err := engineTmpl.Execute(&sb, data)
	return sb.String(), err
}
