// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/common"
	"com.litelake.litecore/config"
	"com.litelake.litecore/container"
)

// InitConfigContainer 初始化配置容器
func InitConfigContainer() (*container.ConfigContainer, error) {
	configContainer := container.NewConfigContainer()

	configProvider, err := config.NewConfigProvider("yaml", "configs/config.yaml")
	if err != nil {
		return nil, err
	}

	container.RegisterConfig[common.BaseConfigProvider](configContainer, configProvider)

	return configContainer, nil
}
