// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/common"
	"com.litelake.litecore/container"
	configproviders "com.litelake.litecore/samples/messageboard/internal/infras/configproviders"
)

// InitConfigContainer 初始化配置容器
func InitConfigContainer() (*container.ConfigContainer, error) {
	configContainer := container.NewConfigContainer()
	configProvider, err := configproviders.NewConfigProvider()
	if err != nil {
		return nil, err
	}

	container.RegisterConfig[common.IBaseConfigProvider](configContainer, configProvider)

	return configContainer, nil
}
