// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/common"
	"github.com/lite-lake/litecore-go/container"
	configproviders "github.com/lite-lake/litecore-go/samples/messageboard/internal/infras/configproviders"
)

// InitConfigContainer 初始化配置容器
func InitConfigContainer() (*container.ConfigContainer, error) {
	configContainer := container.NewConfigContainer()
	configProvider, err := configproviders.NewConfigProvider()
	if err != nil {
		return nil, err
	}

	container.RegisterConfig[common.IBaseConfigProvider](configContainer, configProvider)

	return configContainer, nil
}
