// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/container"
	controllers "com.litelake.litecore/samples/messageboard/internal/controllers"
)

// InitControllerContainer 初始化控制器容器
func InitControllerContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	serviceContainer *container.ServiceContainer,
) *container.ControllerContainer {
	controllerContainer := container.NewControllerContainer(configContainer, managerContainer, serviceContainer)
	container.RegisterController[controllers.IAdminAuthController](controllerContainer, controllers.NewAdminAuthController())
	container.RegisterController[controllers.IMessageAllController](controllerContainer, controllers.NewMessageAllController())
	container.RegisterController[controllers.IMessageCreateController](controllerContainer, controllers.NewMessageCreateController())
	container.RegisterController[controllers.IMessageDeleteController](controllerContainer, controllers.NewMessageDeleteController())
	container.RegisterController[controllers.IMessageListController](controllerContainer, controllers.NewMessageListController())
	container.RegisterController[controllers.IMessageStatusController](controllerContainer, controllers.NewMessageStatusController())
	container.RegisterController[controllers.IPageAdminController](controllerContainer, controllers.NewPageAdminController())
	container.RegisterController[controllers.IPageHomeController](controllerContainer, controllers.NewPageHomeController())
	container.RegisterController[controllers.IResStaticController](controllerContainer, controllers.NewResStaticController())
	container.RegisterController[controllers.ISysHealthController](controllerContainer, controllers.NewSysHealthController())
	container.RegisterController[controllers.ISysMetricsController](controllerContainer, controllers.NewSysMetricsController())

	return controllerContainer
}
