// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/container"
	controllers "com.litelake.litecore/samples/messageboard/internal/controllers"
)

// InitControllerContainer 初始化控制器容器
func InitControllerContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	serviceContainer *container.ServiceContainer,
) *container.ControllerContainer {
	controllerContainer := container.NewControllerContainer(configContainer, managerContainer, serviceContainer)
	container.RegisterController[controllers.IAdminLoginController](controllerContainer, controllers.NewAdminLoginController())
	container.RegisterController[controllers.IAdminPageController](controllerContainer, controllers.NewAdminPageController())
	container.RegisterController[controllers.ICreateMessageController](controllerContainer, controllers.NewCreateMessageController())
	container.RegisterController[controllers.IDeleteMessageController](controllerContainer, controllers.NewDeleteMessageController())
	container.RegisterController[controllers.IGetAllMessagesController](controllerContainer, controllers.NewGetAllMessagesController())
	container.RegisterController[controllers.IGetMessagesController](controllerContainer, controllers.NewGetMessagesController())
	container.RegisterController[controllers.IHealthController](controllerContainer, controllers.NewHealthController())
	container.RegisterController[controllers.IHomePageController](controllerContainer, controllers.NewHomePageController())
	container.RegisterController[controllers.IMetricsController](controllerContainer, controllers.NewMetricsController())
	container.RegisterController[controllers.IResourceStaticController](controllerContainer, controllers.NewResourceStaticController())
	container.RegisterController[controllers.IUpdateStatusController](controllerContainer, controllers.NewUpdateStatusController())

	return controllerContainer
}
