// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/server"
)

// NewEngine 创建应用引擎
func NewEngine() (*server.Engine, error) {
	configContainer, err := InitConfigContainer()
	if err != nil {
		return nil, err
	}

	entityContainer := InitEntityContainer()

	managerContainer, err := InitManagerContainer(configContainer)
	if err != nil {
		return nil, err
	}

	repositoryContainer := InitRepositoryContainer(configContainer, managerContainer, entityContainer)

	serviceContainer := InitServiceContainer(configContainer, managerContainer, repositoryContainer)

	controllerContainer := InitControllerContainer(configContainer, managerContainer, serviceContainer)

	middlewareContainer := InitMiddlewareContainer(configContainer, managerContainer, serviceContainer)

	if err := managerContainer.InjectAll(); err != nil {
		return nil, err
	}
	if err := repositoryContainer.InjectAll(); err != nil {
		return nil, err
	}
	if err := serviceContainer.InjectAll(); err != nil {
		return nil, err
	}
	if err := controllerContainer.InjectAll(); err != nil {
		return nil, err
	}
	if err := middlewareContainer.InjectAll(); err != nil {
		return nil, err
	}

	return server.NewEngine(
		configContainer,
		entityContainer,
		managerContainer,
		repositoryContainer,
		serviceContainer,
		controllerContainer,
		middlewareContainer,
	), nil
}
