// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/server"
)

// NewEngine 创建应用引擎
func NewEngine() (*server.Engine, error) {
	entityContainer := InitEntityContainer()
	repositoryContainer := InitRepositoryContainer(entityContainer)
	serviceContainer := InitServiceContainer(repositoryContainer)
	controllerContainer := InitControllerContainer(serviceContainer)
	middlewareContainer := InitMiddlewareContainer(serviceContainer)

	return server.NewEngine(
		&server.BuiltinConfig{
			Driver:   "yaml",
			FilePath: "configs/config.yaml",
		},
		entityContainer,
		repositoryContainer,
		serviceContainer,
		controllerContainer,
		middlewareContainer,
	), nil
}
