// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/container"
	"github.com/lite-lake/litecore-go/common"
	entities "github.com/lite-lake/litecore-go/samples/messageboard/internal/entities"
)

// InitEntityContainer Initialize entity container
func InitEntityContainer() *container.EntityContainer {
	entityContainer := container.NewEntityContainer()
	container.RegisterEntity[common.IBaseEntity](entityContainer, &entities.Message{})

	return entityContainer
}
