// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/common"
	"com.litelake.litecore/container"
	entities "com.litelake.litecore/samples/messageboard/internal/entities"
)

// InitEntityContainer 初始化实体容器
func InitEntityContainer() *container.EntityContainer {
	entityContainer := container.NewEntityContainer()
	container.RegisterEntity[common.BaseEntity](entityContainer, &entities.Message{})

	return entityContainer
}
