// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/container"
	listeners "github.com/lite-lake/litecore-go/samples/messageboard/internal/listeners"
)

// InitListenerContainer 初始化监听器容器
func InitListenerContainer(serviceContainer *container.ServiceContainer) *container.ListenerContainer {
	listenerContainer := container.NewListenerContainer(serviceContainer)

	container.RegisterListener[listeners.IMessageCreatedListener](listenerContainer, listeners.NewMessageCreatedListener())
	container.RegisterListener[listeners.IMessageAuditListener](listenerContainer, listeners.NewMessageAuditListener())

	return listenerContainer
}
