// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/container"
	listeners "github.com/lite-lake/litecore-go/samples/messageboard/internal/listeners"
)

// InitListenerContainer Initialize listener container
func InitListenerContainer(serviceContainer *container.ServiceContainer) *container.ListenerContainer {
	listenerContainer := container.NewListenerContainer(serviceContainer)
	container.RegisterListener[listeners.IMessageAuditListener](listenerContainer, listeners.NewMessageAuditListener())
	container.RegisterListener[listeners.IMessageCreatedListener](listenerContainer, listeners.NewMessageCreatedListener())

	return listenerContainer
}
