// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"reflect"

	"com.litelake.litecore/common"
	"com.litelake.litecore/container"
	infras "com.litelake.litecore/samples/messageboard/internal/infras"
)

// InitManagerContainer 初始化管理器容器
func InitManagerContainer(configContainer *container.ConfigContainer) (*container.ManagerContainer, error) {
	managerContainer := container.NewManagerContainer(configContainer)

	configProvider := configContainer.GetByType(reflect.TypeOf((*common.IBaseConfigProvider)(nil)).Elem())
	_ = configProvider
	managerCacheManager, err := infras.NewCacheManager(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[infras.CacheManager](managerContainer, managerCacheManager)
	managerDatabaseManager, err := infras.NewDatabaseManager(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[infras.DatabaseManager](managerContainer, managerDatabaseManager)
	managerLoggerManager, err := infras.NewLoggerManager(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[infras.LoggerManager](managerContainer, managerLoggerManager)
	managerTelemetryManager, err := infras.NewTelemetryManager(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[infras.TelemetryManager](managerContainer, managerTelemetryManager)

	return managerContainer, nil
}
