// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"reflect"

	"github.com/lite-lake/litecore-go/common"
	"github.com/lite-lake/litecore-go/container"
	managers "github.com/lite-lake/litecore-go/samples/messageboard/internal/infras/managers"
)

// InitManagerContainer 初始化管理器容器
func InitManagerContainer(configContainer *container.ConfigContainer) (*container.ManagerContainer, error) {
	managerContainer := container.NewManagerContainer(configContainer)

	configProvider := configContainer.GetByType(reflect.TypeOf((*common.IBaseConfigProvider)(nil)).Elem())
	_ = configProvider
	managerCacheManager, err := managers.NewCacheManager(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[managers.ICacheManager](managerContainer, managerCacheManager)
	managerDatabaseManager, err := managers.NewDatabaseManager(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[managers.IDatabaseManager](managerContainer, managerDatabaseManager)
	managerLoggerManager, err := managers.NewLoggerManager(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[managers.ILoggerManager](managerContainer, managerLoggerManager)
	managerTelemetryManager, err := managers.NewTelemetryManager(configProvider)
	if err != nil {
		return nil, err
	}
	container.RegisterManager[managers.ITelemetryManager](managerContainer, managerTelemetryManager)

	return managerContainer, nil
}
