// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/container"
	middlewares "github.com/lite-lake/litecore-go/samples/messageboard/internal/middlewares"
)

// InitMiddlewareContainer Initialize middleware container
func InitMiddlewareContainer(serviceContainer *container.ServiceContainer) *container.MiddlewareContainer {
	middlewareContainer := container.NewMiddlewareContainer(serviceContainer)
	container.RegisterMiddleware[middlewares.IAuthMiddleware](middlewareContainer, middlewares.NewAuthMiddleware())
	container.RegisterMiddleware[middlewares.ICorsMiddleware](middlewareContainer, middlewares.NewCorsMiddleware())
	container.RegisterMiddleware[middlewares.IRateLimiterMiddleware](middlewareContainer, middlewares.NewRateLimiterMiddleware())
	container.RegisterMiddleware[middlewares.IRecoveryMiddleware](middlewareContainer, middlewares.NewRecoveryMiddleware())
	container.RegisterMiddleware[middlewares.IRequestLoggerMiddleware](middlewareContainer, middlewares.NewRequestLoggerMiddleware())
	container.RegisterMiddleware[middlewares.ISecurityHeadersMiddleware](middlewareContainer, middlewares.NewSecurityHeadersMiddleware())
	container.RegisterMiddleware[middlewares.ITelemetryMiddleware](middlewareContainer, middlewares.NewTelemetryMiddleware())

	return middlewareContainer
}
