// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/container"
	middlewares "com.litelake.litecore/samples/messageboard/internal/middlewares"
)

// InitMiddlewareContainer 初始化中间件容器
func InitMiddlewareContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	serviceContainer *container.ServiceContainer,
) *container.MiddlewareContainer {
	middlewareContainer := container.NewMiddlewareContainer(configContainer, managerContainer, serviceContainer)
	container.RegisterMiddleware[middlewares.IAuthMiddleware](middlewareContainer, middlewares.NewAuthMiddleware())
	container.RegisterMiddleware[middlewares.ICorsMiddleware](middlewareContainer, middlewares.NewCorsMiddleware())
	container.RegisterMiddleware[middlewares.IRecoveryMiddleware](middlewareContainer, middlewares.NewRecoveryMiddleware())
	container.RegisterMiddleware[middlewares.IRequestLoggerMiddleware](middlewareContainer, middlewares.NewRequestLoggerMiddleware())
	container.RegisterMiddleware[middlewares.ISecurityHeadersMiddleware](middlewareContainer, middlewares.NewSecurityHeadersMiddleware())
	container.RegisterMiddleware[middlewares.ITelemetryMiddleware](middlewareContainer, middlewares.NewTelemetryMiddleware())

	return middlewareContainer
}
