// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/container"
	middlewares "com.litelake.litecore/samples/messageboard/internal/middlewares"
)

// InitMiddlewareContainer 初始化中间件容器
func InitMiddlewareContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	serviceContainer *container.ServiceContainer,
) *container.MiddlewareContainer {
	middlewareContainer := container.NewMiddlewareContainer(configContainer, managerContainer, serviceContainer)
	container.RegisterMiddleware[middlewares.IAuthMiddleware](middlewareContainer, middlewares.NewAuthMiddleware())

	return middlewareContainer
}
