// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"com.litelake.litecore/container"
	repositories "com.litelake.litecore/samples/messageboard/internal/repositories"
)

// InitRepositoryContainer 初始化仓储容器
func InitRepositoryContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	entityContainer *container.EntityContainer,
) *container.RepositoryContainer {
	repositoryContainer := container.NewRepositoryContainer(configContainer, managerContainer, entityContainer)
	container.RegisterRepository[repositories.IMessageRepository](repositoryContainer, repositories.NewMessageRepository())

	return repositoryContainer
}
