// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/container"
	schedulers "github.com/lite-lake/litecore-go/samples/messageboard/internal/schedulers"
)

// InitSchedulerContainer 初始化定时器容器
func InitSchedulerContainer(serviceContainer *container.ServiceContainer) *container.SchedulerContainer {
	schedulerContainer := container.NewSchedulerContainer(serviceContainer)
	container.RegisterScheduler[schedulers.ICleanupScheduler](schedulerContainer, schedulers.NewCleanupScheduler())
	container.RegisterScheduler[schedulers.IStatisticsScheduler](schedulerContainer, schedulers.NewStatisticsScheduler())

	return schedulerContainer
}
