// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/container"
	services "github.com/lite-lake/litecore-go/samples/messageboard/internal/services"
)

// InitServiceContainer 初始化服务容器
func InitServiceContainer(
	configContainer *container.ConfigContainer,
	managerContainer *container.ManagerContainer,
	repositoryContainer *container.RepositoryContainer,
) *container.ServiceContainer {
	serviceContainer := container.NewServiceContainer(configContainer, managerContainer, repositoryContainer)
	container.RegisterService[services.IAuthService](serviceContainer, services.NewAuthService())
	container.RegisterService[services.IHTMLTemplateService](serviceContainer, services.NewHTMLTemplateService())
	container.RegisterService[services.IMessageService](serviceContainer, services.NewMessageService())
	container.RegisterService[services.ISessionService](serviceContainer, services.NewSessionService())

	return serviceContainer
}
