// Code generated by litecore/cli. DO NOT EDIT.
package application

import (
	"github.com/lite-lake/litecore-go/container"
	services "github.com/lite-lake/litecore-go/samples/messageboard/internal/services"
)

// InitServiceContainer Initialize service container
func InitServiceContainer(repositoryContainer *container.RepositoryContainer) *container.ServiceContainer {
	serviceContainer := container.NewServiceContainer(repositoryContainer)
	container.RegisterService[services.IAuthService](serviceContainer, services.NewAuthService())
	container.RegisterService[services.IHTMLTemplateService](serviceContainer, services.NewHTMLTemplateService())
	container.RegisterService[services.IMessageService](serviceContainer, services.NewMessageService())
	container.RegisterService[services.ISessionService](serviceContainer, services.NewSessionService())

	return serviceContainer
}
